### ISSUE TITLE
Can it be installed in Hassio?

### ISSUE THREAD

**Issue by euqiuq** [nunolopes/ecoforest-proxy#4]
Hi, I hope you are doing well!

First of all, thank you very much for your work!

I was wondering if this development can be installed in Hassio, and if possible, how could it be done?

Greetings and thank you very much in advance for your help, 

Enrique.

**Comment by nunolopes** [comment]
Hi Enrique, 

Thanks! Someone has forked this work and made available a addon for hassio: https://github.com/joseal/hassio-addons.

I haven't tried it since I'm not using hassio but that might help you.

**Comment by euqiuq** [comment]
Hi Nuno,

Thank you so much for your quick response!

I have tried the addon you resend me, but I think I might be
doing something wrong because it is not working.
I have wrote to Jose, the gay who has forked your work.

Basically, told him:

I have tried this addon for Hassio, but I am not getting the expected
result, it is not working :-(

This is my configuration in the addon (I am not getting any error in the
log):

debug: '0'
proxy_port: '8000'
ecoforest_host: 'https://192.168.1.133:8000'
ecoforest_user: '1234567890'
ecoforest_pass: pass

This is my configuration in Configuration.yaml

  - platform: rest
    name: ecoforest
    resource: 'http://192.168.1.133:8000/ecoforest/fullstats'
    method: 'GET'
    scan_interval: 10
    force_update: true
    json_attributes:
      - temperatura
      - consigna_potencia
      - modo_func
      - modo_operacion
      - state
      - on_off
      - consigna_temperatura
      - estado
      - error_MODO_on_off
  - platform: template
    sensors:
      ecoforest_status:
        entity_id: sensor.ecoforest
        friendly_name: "Status"
        value_template: "{{ state_attr('sensor.ecoforest', 'state') }}"
      ecoforest_temp:
        entity_id: sensor.ecoforest
        friendly_name: "Temperature"
        unit_of_measurement: "°C"
        value_template: "{{ state_attr('sensor.ecoforest',
'consigna_temperatura') }}"
      ecoforest_potencia:
        entity_id: sensor.ecoforest
        friendly_name: "Power"
        value_template: "{{ state_attr('sensor.ecoforest',
'consigna_potencia') }}"
      ecoforest_room_temp:
        entity_id: sensor.ecoforest
        friendly_name: "Room Temperature"
        unit_of_measurement: "°C"
        value_template: "{{ state_attr('sensor.ecoforest', 'temperatura')
}}"

Is there any way to connect to the easynet2.ecoforest.es:15614 server
instead of the local connection?

Best regards,

Enrique.

**Comment by nunolopes** [comment]
No, I haven't tried connecting to ecoforest's server, I actually have that blocked in my firewall.
